name: Build and Deploy to Google Cloud Platform

on:
  push:
    branches: 
      - main

env:
  IMAGE_NAME: '${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -f Edulingual.Api/Dockerfile -t "${{ env.IMAGE_NAME }}"
      
      - name: Authenticate docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PWD }}

      - name: Push docker image
        run: docker push "${{ env.IMAGE_NAME }}"

  deploy:
    need: publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
    
      - name: Configure SSH Key
        run: |
          mkdir -p $HOME/.ssh
          touch $HOME/.ssh/edulingual_vm_key
          echo "${{ secrets.EDULINGUAL_SSH_KEY }}" > $HOME/.ssh/edulingual_vm_key
          chmod 600 $HOME/.ssh/edulingual_vm_key
      
      - name: Deploy to Google Cloud Platform
        run: |
          ssh -i ~/.ssh/edulingual_vm_key \
                    -o StrictHostKeyChecking=no \
                    ${{ secrets.EDULINGUAL_VM_USERNAME }}@${{ secrets.EDULINGUAL_VM_IP_ADDRESS }} \
                     '
                      sudo -i &&
                      docker ps -q | xargs -r docker stop &&
                      docker container prune -f &&
                      docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PWD }} &&
                      docker image pull ${{ env.IMAGE_NAME }}
                      docker run -d --name ${{ env.IMAGE_NAME }} -p 8080:8080 ${{ env.IMAGE_NAME }}'
